export const ErrorCode = {
  // HTTP Errors
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Auth Errors
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_MISSING: 'TOKEN_MISSING',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_INVALID: 'MFA_INVALID',
  OAUTH_ERROR: 'OAUTH_ERROR',

  // Domain Errors
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  INVARIANT_VIOLATION: 'INVARIANT_VIOLATION',
  ENTITY_STATE_ERROR: 'ENTITY_STATE_ERROR',
  CONCURRENCY_ERROR: 'CONCURRENCY_ERROR',
  IDEMPOTENCY_ERROR: 'IDEMPOTENCY_ERROR',

  // Organization Errors
  ORG_SUBSCRIPTION_REQUIRED: 'ORG_SUBSCRIPTION_REQUIRED',
  ORG_MEMBER_LIMIT_EXCEEDED: 'ORG_MEMBER_LIMIT_EXCEEDED',
  ORG_INVITATION_EXPIRED: 'ORG_INVITATION_EXPIRED',

  // Project Errors
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  SPRINT_ALREADY_ACTIVE: 'SPRINT_ALREADY_ACTIVE',
  SPRINT_NOT_STARTED: 'SPRINT_NOT_STARTED',

  // File Errors
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',

  // Billing Errors
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',
} as const;

export type ErrorCodeKey = (typeof ErrorCode)[keyof typeof ErrorCode];
